spring:
  jpa:
    show-sql: true
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        show_sql : true
        use_sql_comments : true
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  datasource:
    driver-class-name : org.h2.Driver
    url: jdbc:h2:mem:voting
    username: sa
    password:
    data : classpath:/db/data.sql
  h2:
    console:
      enabled: true
      path: /console
  mvc:
    format:
      date: yyyy-MM-dd